FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install -g npm@10.2.1
RUN rm -rf node_modules package-lock.json
RUN npm cache clean -f
RUN npm install

COPY . .

CMD [ "npm", "run", "dev" ]
